select * from customer limit 20

--what is the total revenue generated by male and fremale
select gender , SUM(purchase_amount) from customer
group by gender

--which customer used the discount but still spent more than the average purchase amount
select customer_id , purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--which are the top 5 products with the highest review ratings
select item_purchased , ROUND(AVG(review_rating :: numeric) , 2) as "Average Review Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--compare the average purchase amount between standard and express shipping process
select shipping_type , ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard' , 'Express')
group by shipping_type

--do subscribed customers spend more? compare average spend and total revenue between subscribed and unsubscribed 
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue , avg_spend

--which 5 products have the highest percentage of purchases with discounts applied

select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' then 1 else 0 end)/ COUNT(*),2) as discount_applied
from customer
group by item_purchased
order by discount_applied limit 5

--are customers who are repeat buyers are also the subscribers ?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--what is the revenue contribution of each age group    
select age_group,
ROUND(SUM(purchase_amount) , 2) as total_revenue
from customer
group by age_group
order by total_revenue desc


